name: starbhak_mart_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.3 #latest version
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.6
  clippy_flutter: 2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
